const GOOGLE_KEY = process.env.GOOGLE_PLACES_API_KEY;

async function travelTimeMinutes(placeIdA, placeIdB) {
  if (!placeIdA || !placeIdB) return null;
  const url = 'https://routes.googleapis.com/directions/v2:computeRoutes';
  const res = await fetch(url, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'X-Goog-Api-Key': GOOGLE_KEY,
      'X-Goog-FieldMask': 'routes.duration',
    },
    body: JSON.stringify({
      origin: { placeId: placeIdA },
      destination: { placeId: placeIdB },
      travelMode: 'DRIVE',
    }),
  });
  const data = await res.json();
  const durationStr = data.routes?.[0]?.duration; // e.g. "540s"
  if (!durationStr) return null;
  return Math.round(parseInt(durationStr, 10) / 60);
}

export async function attachTravelTimes(itinerary) {
  for (const day of itinerary.days || []) {
    for (let i = 1; i < day.items.length; i++) {
      const prev = day.items[i - 1];
      const curr = day.items[i];
      try {
        curr.travelFromPrevMin = await travelTimeMinutes(prev.placeId, curr.placeId);
      } catch {
        curr.travelFromPrevMin = null; // non-fatal — timing degrades gracefully
      }
    }
  }
  return itinerary;
}

// NOTE: computeBudgetBreakdown() was removed — the budget breakdown is now
// generated by the AI itself (itineraryService.js) from the real hotel,
// meal, and activity prices it picked, not a fixed percentage split.